# Домашняя работа. Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [1]:
import numpy as np

2) Создать нулевой вектор размера 10

In [2]:

zero_vector = np.zeros(10)
print(zero_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3) Создать вектор заполненный 7-ами размера 7

In [3]:

vector = np.full(7, 7)
print(vector)

[7 7 7 7 7 7 7]


4) Создать вектор заполненный четными числами от 10 до 100

In [4]:

even_vector = np.arange(10, 101, 2)
print(even_vector)

[ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100]


5) Создать массив случайных чисел и развернуть его задом наперёд

In [5]:

random_array = np.random.rand(10)

reversed_array = random_array[::-1]

print("Оригинальный массив:", random_array)
print("Развернутый массив:", reversed_array)

Оригинальный массив: [0.46593366 0.08338837 0.98939481 0.1908386  0.24302848 0.50267807
 0.00908277 0.91866989 0.34758947 0.38602321]
Развернутый массив: [0.38602321 0.34758947 0.91866989 0.00908277 0.50267807 0.24302848
 0.1908386  0.98939481 0.08338837 0.46593366]


6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [6]:

matrix = np.arange(9).reshape(3, 3)

print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [7]:

matrix = np.eye(4, k=1)

print(matrix)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [8]:

matrix = np.full((4, 4), 7)

np.fill_diagonal(matrix, np.arange(1, 5))

print(matrix)

[[1 7 7 7]
 [7 2 7 7]
 [7 7 3 7]
 [7 7 7 4]]


9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [16]:
matrix = np.tile(np.arange(5), (5, 1))
print(matrix_1)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [17]:

matrix = np.random.rand(10, 10)
mean_row = matrix.mean(axis=1, keepdims=True)
matrix_res = matrix - mean_row
print(matrix_res)

[[-0.05421504 -0.42373496  0.2060602  -0.10803613  0.47052752 -0.06955388
  -0.29640058  0.54472143  0.13227264 -0.40164121]
 [-0.26892187  0.22614968  0.13210515 -0.40737377  0.02344391  0.13531198
   0.19349772  0.05425546 -0.12338678  0.03491853]
 [-0.52673314  0.31232337 -0.32066101  0.33187733 -0.0080119   0.20425831
   0.18736679 -0.36410462 -0.01331712  0.197002  ]
 [ 0.28967777 -0.06825136 -0.11255115  0.36130872 -0.32824333  0.02133157
  -0.27830978 -0.21585619  0.24682465  0.08406909]
 [-0.28637534  0.16235704  0.4853095  -0.34854892  0.0276458  -0.14070638
  -0.10703731  0.38436993  0.07269861 -0.24971293]
 [-0.01831889 -0.27463415 -0.43037152 -0.2790511   0.35141029  0.17536964
  -0.06168889  0.24733045 -0.02621981  0.31617399]
 [ 0.24218746  0.15469271  0.09846499  0.21906987  0.32676634 -0.45340854
  -0.30743285 -0.00940234 -0.29030239  0.01936476]
 [-0.27714094 -0.22338817  0.32751093 -0.19380261 -0.24473928 -0.31282261
   0.0525282  -0.18457341  0.46665963  0.58976826]


11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [18]:

matrix = np.random.rand(10, 10)
median_col = np.median(matrix, axis=0)
matrix_res = matrix - median_col
print(matrix_res)

[[-0.2541178   0.12378716 -0.04721341  0.52592326  0.15987352 -0.00573966
   0.25786301  0.43289347  0.70635635  0.20560182]
 [-0.18739634 -0.19077503  0.3363787   0.22175912  0.03370077 -0.29655406
  -0.50965398 -0.07541106 -0.24400482 -0.21717194]
 [ 0.06923447  0.62356553 -0.05671917 -0.16607744  0.57695179 -0.02336897
  -0.15300923 -0.18169998 -0.07942415  0.01878333]
 [ 0.20933402  0.02313005  0.33095163 -0.23713243  0.6389202  -0.22526445
   0.17387175  0.07233858 -0.18098778 -0.09689603]
 [ 0.22832307 -0.28646341  0.21537341  0.16607744 -0.10282537  0.06752437
  -0.55017938 -0.25428882  0.23678909 -0.08002248]
 [-0.10219851 -0.02313005  0.17232665  0.45168048 -0.03370077  0.20796074
   0.0799611  -0.13803511  0.44816207  0.21589069]
 [-0.07441572 -0.02808791 -0.31650797 -0.17117682 -0.10547327  0.17527087
   0.15064866  0.14060943  0.02430948  0.38555422]
 [ 0.13469616 -0.13695508  0.04721341 -0.21867005 -0.2498483   0.29558828
  -0.0799611   0.22261807 -0.11049268  0.09753603]


12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [21]:

matrix = np.random.rand(5, 5)
max_in_rows = matrix.max(axis=1, keepdims=True)
min_in_rows = matrix.min(axis=1, keepdims=True)
matrix_res = np.hstack((matrix, max_in_rows, min_in_rows))
print(matrix)
print(max_in_rows)
print(min_in_rows)
print(matrix_res)

[[0.77761171 0.45867561 0.30387228 0.68636004 0.68898761]
 [0.91594088 0.06741081 0.46110485 0.37205391 0.19640341]
 [0.3696298  0.25056703 0.39446591 0.28749602 0.95509833]
 [0.60820673 0.59151976 0.45877604 0.48916046 0.98432833]
 [0.38368513 0.68425356 0.89363098 0.30009299 0.09918025]]
[[0.77761171]
 [0.91594088]
 [0.95509833]
 [0.98432833]
 [0.89363098]]
[[0.30387228]
 [0.06741081]
 [0.25056703]
 [0.45877604]
 [0.09918025]]
[[0.77761171 0.45867561 0.30387228 0.68636004 0.68898761 0.77761171
  0.30387228]
 [0.91594088 0.06741081 0.46110485 0.37205391 0.19640341 0.91594088
  0.06741081]
 [0.3696298  0.25056703 0.39446591 0.28749602 0.95509833 0.95509833
  0.25056703]
 [0.60820673 0.59151976 0.45877604 0.48916046 0.98432833 0.98432833
  0.45877604]
 [0.38368513 0.68425356 0.89363098 0.30009299 0.09918025 0.89363098
  0.09918025]]


13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [29]:

vector = np.arange(1, 52)

odd_vector = vector[vector % 2 != 0][:25].reshape(5, 5)  
even_vector = vector[vector % 2 == 0][:25].reshape(5, 5)  

product_matrix = np.dot(odd_vector, even_vector)
print("Произведение матриц:\n", product_matrix)

det = np.linalg.det(product_matrix)
print("\nОпределитель матрицы:", det)

if det != 0:
    inverse_matrix = np.linalg.inv(product_matrix)
    print("\nОбратная матрица:\n", inverse_matrix)
else:
    print("\nМатрица является вырожденной и не имеет обратной матрицы.")

#или это не работает так матрица получается не квадратной =)


Произведение матриц:
 [[ 750  800  850  900  950]
 [1850 2000 2150 2300 2450]
 [2950 3200 3450 3700 3950]
 [4050 4400 4750 5100 5450]
 [5150 5600 6050 6500 6950]]

Определитель матрицы: 0.0

Матрица является вырожденной и не имеет обратной матрицы.


14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами. 

In [31]:

chessboard_matrix = np.zeros((8, 8), dtype=int)
chessboard_matrix[1::2, ::2] = 1
chessboard_matrix[::2, 1::2] = 1
print(chessboard_matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [4]:
import numpy as np

vector = np.arange(1, 52)

odd_vector = vector[vector % 2 != 0].reshape(-1, 1)  
even_vector = vector[vector % 2 == 0].reshape(1, -1)

product_matrix = np.dot(odd_vector, even_vector)
print("Произведение матриц:\n", product_matrix)

rows, cols = product_matrix.shape

print("Количество строк:", rows)
print("Количество столбцов:", cols)

Произведение матриц:
 [[   2    4    6    8   10   12   14   16   18   20   22   24   26   28
    30   32   34   36   38   40   42   44   46   48   50]
 [   6   12   18   24   30   36   42   48   54   60   66   72   78   84
    90   96  102  108  114  120  126  132  138  144  150]
 [  10   20   30   40   50   60   70   80   90  100  110  120  130  140
   150  160  170  180  190  200  210  220  230  240  250]
 [  14   28   42   56   70   84   98  112  126  140  154  168  182  196
   210  224  238  252  266  280  294  308  322  336  350]
 [  18   36   54   72   90  108  126  144  162  180  198  216  234  252
   270  288  306  324  342  360  378  396  414  432  450]
 [  22   44   66   88  110  132  154  176  198  220  242  264  286  308
   330  352  374  396  418  440  462  484  506  528  550]
 [  26   52   78  104  130  156  182  208  234  260  286  312  338  364
   390  416  442  468  494  520  546  572  598  624  650]
 [  30   60   90  120  150  180  210  240  270  300  330  360  390  